configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "your-rds-endpoint"
  DB_DATABASE: "your-db-name"
  DB_USERNAME: "your-db-user"
  DB_PASSWORD: "your-db-password"